name: livestream
description: A Live Streaming Mobile & Web Application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #STYLING & ANIMATIONS
  cupertino_icons: ^1.0.2
  lottie: ^1.0.1
  rive: ^0.10.1
  eva_icons_flutter: ^3.1.0
  animate_icons: ^2.0.0
  animated_splash_screen: ^1.3.0
  google_fonts: ^4.0.1
  flutter_switch: ^0.3.2
  cool_alert: ^1.1.0
  auto_size_text: ^3.0.0
  font_awesome_flutter: ^10.4.0
  dotted_border: ^2.0.0+3
  #SAVE DATA
  firebase_core: ^2.7.0
  firebase_core_web: ^2.2.1
  firebase_auth: ^4.2.9
  cloud_firestore: ^4.4.3
  firebase_storage: ^11.1.0
  flutter_secure_storage: ^8.0.0
  get: ^4.6.5
  get_storage: ^2.1.1
  #LIVE STREAM
  agora_rtc_engine: ^5.0.1
  agora_rtm: ^1.5.0
  uuid: ^3.0.7
  http: ^0.13.5
  #WATCH VIDEOS
  video_player: ^2.6.1
  chewie: ^1.4.0
  like_button: ^2.0.5 #ANIMATED LOVE REACT
  #OTHER
  provider: ^6.0.5 #STATE MANAGEMENT
  google_sign_in: ^6.0.2 #LOGIN WITH A GOOGLE ACCOUNT
  flutter_facebook_auth: ^5.0.8 #LOGIN WITH A FACEBOOK ACCOUNT
  easy_localization: ^3.0.1 #INTERNATIONALIZATION
  connectivity_plus: ^3.0.3 #CHECK INTERNET CONNECTIVITY
  file_picker: ^5.2.6 #PICK FILES FROM DEVICE
  permission_handler: ^10.2.0 #HANDLES NEEDED PERMISSIONS
  textfield_tags: ^2.0.2 #TAG TEXT FIELD
  flutter_dotenv: ^5.0.2 #DOTENV FILE MANAGEMENT
  language_picker: ^0.4.3 #LANGUAGE PICKER WITH ALL THE LANGUAGES
  url_launcher: ^6.1.11 #LAUNCH URLS
  flutter_rating_bar: ^4.0.1 #USER CAN RATE TEH APP FROM 1 TO 5
  intl: ^0.18.0 #USED TO FORMAT THE DATES
  timeago: ^3.4.0 #USED TO FORMAT THE DATES
  #STILL TESTING THESE



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  background_color: "#ffffff"



  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#ffffff"


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/rive/
    - assets/lottie/
    - assets/translations/
    - .env