name: bitrate_realm
description: A Live Streaming Mobile & Web Application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #----------------------STYLING & ANIMATION----------------------
  cupertino_icons: ^1.0.8
  lottie: any
  rive: any
  eva_icons_flutter: ^3.1.0
  animate_icons: ^2.0.0
  animated_splash_screen: ^1.3.0
  google_fonts: any
  flutter_switch: ^0.3.2
  cool_alert: ^2.0.1
  auto_size_text: ^3.0.0
  font_awesome_flutter: ^10.8.0
  dotted_border: ^2.1.0



  #----------------------SAVE DATA----------------------
  firebase_core: any
#  firebase_core_web: ^2.18.2
  firebase_auth: any
  cloud_firestore: any
  firebase_storage: any

  flutter_secure_storage: any
  get: ^4.6.6
  get_storage: ^2.1.1
  #----------------------LIVE STREAM----------------------
  agora_rtc_engine: ^5.0.1
  agora_rtm: ^1.5.0
  uuid: ^4.5.1
  http: any


  #WATCH VIDEOS
  video_player: any
  chewie: any
  like_button: ^2.0.5 #ANIMATED LOVE REACT
  #OTHER
  provider: ^6.1.2 #STATE MANAGEMENT
  google_sign_in: any #LOGIN WITH A GOOGLE ACCOUNT
  easy_localization: any #INTERNATIONALIZATION
  file_picker: any #PICK FILES FROM DEVICE
  permission_handler: any #HANDLES NEEDED PERMISSIONS
  textfield_tags: any #TAG TEXT FIELD
  flutter_dotenv: any #DOTENV FILE MANAGEMENT
  language_picker: any #LANGUAGE PICKER WITH ALL THE LANGUAGES
  url_launcher: any #LAUNCH URLS
  flutter_rating_bar: ^4.0.1 #USER CAN RATE TEH APP FROM 1 TO 5
  intl: any #USED TO FORMAT THE DATES
  timeago: any #USED TO FORMAT THE DATES
  flutter_staggered_grid_view: ^0.7.0

  #----------------------TESTING----------------------
#  flutter_animate: ^4.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: any
  flutter_launcher_icons: any

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  background_color: "#ffffff"
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#ffffff"


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/rive/
    - assets/lottie/
    - assets/translations/
    - .env