// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4dwoyPrnjHGfeSFfUsaVCzx5QbBP6YLs',
    appId: '1:658040305529:web:46f66e20b3a2b93b4b21a8',
    messagingSenderId: '658040305529',
    projectId: 'bitrate-realm',
    authDomain: 'bitrate-realm.firebaseapp.com',
    storageBucket: 'bitrate-realm.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkItl4Yo_DTIzn089En0OmRCB93_D1UG4',
    appId: '1:658040305529:android:f3eb9814edd243574b21a8',
    messagingSenderId: '658040305529',
    projectId: 'bitrate-realm',
    storageBucket: 'bitrate-realm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC568jwNoJIjzCR0TnbfKKWmmByo2qQ0M8',
    appId: '1:658040305529:ios:06f248a566111d8a4b21a8',
    messagingSenderId: '658040305529',
    projectId: 'bitrate-realm',
    storageBucket: 'bitrate-realm.appspot.com',
    androidClientId: '658040305529-5co991n1vao18hb0s84igpevph4qqmh3.apps.googleusercontent.com',
    iosClientId: '658040305529-707hafsffv0b7im11a9llt9m33h2japb.apps.googleusercontent.com',
    iosBundleId: 'com.example.livestream',
  );
}
